"""Recreate users table

Revision ID: 483b053c1e21
Revises: 4879545917d2
Create Date: 2025-04-30 21:50:12.004883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483b053c1e21'
down_revision: Union[str, None] = '4879545917d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('surname', sa.String, nullable=False),
        sa.Column('email', sa.String, nullable=False, unique=True),
        sa.Column('phone', sa.String, nullable=True),
        sa.Column('password', sa.String, nullable=False),
        sa.Column('is_admin', sa.Boolean, nullable=False, default=False),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('users')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # ### end Alembic commands ###
